-----------------------------------------------
CREATE TABLE T_MAJOR_AVG_RES(
	MAJOR VARCHAR2(20),
	RESULT NUMBER(5, 2)
);
DROP TABLE T_MAJOR_AVG_RES;
COMMIT;
CREATE OR REPLACE PROCEDURE P_MAJOR_AVG_RES
IS 
	CURSOR CUR_MAJOR_AVG_RES IS 
		SELECT ST.MAJOR
			 , AVG(SC.RESULT)
			FROM STUDENT ST
			JOIN SCORE SC
			  ON ST.SNO = SC.SNO
            GROUP BY ST.MAJOR;
BEGIN
	FOR MAJOR_AVG_RES_ROW IN CUR_MAJOR_AVG_RES LOOP
		INSERT INTO T_MAJOR_AVG_RES
		VALUES MAJOR_AVG_RES_ROW;
		COMMIT;
	END LOOP;
END;
/
EXEC P_MAJOR_AVG_RES;

SELECT *
	FROM T_MAJOR_AVG_RES;
----------------------------------------------   
CREATE OR REPLACE FUNCTION F_GET_VACATION_CNT
(
	INSICDATE DATE
)
RETURN NUMBER
IS 
BEGIN 
	RETURN TRUNC((SYSDATE - INSICDATE) / 1825, 0);
END;
/
SELECT F_GET_VACATION_CNT(TO_DATE('19880624', 'YYYYMMDD'))
	FROM DUAL;