--1) ������ ������ �⸻���� ��� ������ ���� ���̺� T_MAJOR_AVG_RES�� �����ϰ�
--   SCORE���̺��� STUDENT���̺��� �����ؼ�
--   T_MAJOR_AVG_RES�� �����͸� �����ϴ� ���ν��� P_MAJOR_AVG_RES�� �����ϼ���.
CREATE TABLE T_MAJOR_AVG_RES(
    MAJOR VARCHAR2(20),
    AVG_RES NUMBER(5, 2)
);

CREATE OR REPLACE PROCEDURE P_MAJOR_AVG_RES
IS
    CURSOR CUR_MAJOR_AVG_RES IS
        SELECT ST.MAJOR
             , ROUND(AVG(SC.RESULT), 2)
            FROM STUDENT ST
            JOIN SCORE SC
              ON ST.SNO = SC.SNO
            GROUP BY ST.MAJOR;
BEGIN
    FOR MAJOR_AVG_RES_ROW IN CUR_MAJOR_AVG_RES LOOP
        INSERT INTO T_MAJOR_AVG_RES
        VALUES MAJOR_AVG_RES_ROW;
    END LOOP;
END;
/

EXEC P_MAJOR_AVG_RES;

SELECT *
    FROM T_MAJOR_AVG_RES;

--2) �������� �����Ϸκ��� 5�⸶�� �Ƚĳ��� �����ϴ�.
--   �������� ���ó�¥������ �Ƚĳ� Ƚ���� �����ϴ� �Լ� F_GET_VACATION_CNT�� �����ϼ���
CREATE OR REPLACE FUNCTION F_GET_VACATION_CNT(
    SABB DATE
)
RETURN NUMBER
IS
    CURR_DATE DATE := SYSDATE;
    VACATION_CNT NUMBER;
BEGIN
    VACATION_CNT := TRUNC(MONTHS_BETWEEN(CURR_DATE, SABB) / 60);
    RETURN VACATION_CNT;
END;
/

SELECT F_GET_VACATION_CNT('1994-02-17') FROM DUAL;

DROP TABLE T_MAJOR_AVG_RES;
DROP TABLE P_MAJOR_AVG_RES;
DROP TABLE T_MAJOR_AVG_RES;