--1) 전공과 전공별 기말고사 평균 점수를 갖는 테이블 T_MAJOR_AVG_RES를 생성하고
--   SCORE테이블과 STUDENT테이블을 참조해서
--   T_MAJOR_AVG_RES에 데이터를 저장하는 프로시저 P_MAJOR_AVG_RES를 생성하세요.
CREATE TABLE T_MAJOR_AVG_RES AS
SELECT ST.MAJOR,
     , ROUND(AVG(SC.RESULT), 2) AS RE_AVG
    FROM STUDENT ST
    JOIN SCORE SC
      ON ST.SNO = SC.SNO
    GROUP BY ST.MAJOR;

CREATE OR REPLACE PROCEDURE P_MAJOR_AVG_RES
IS
BEGIN
    INSERT INTO T_MAJOR_AVG_RES
SELECT ST.MAJOR,
     , ROUND(AVG(SC.RESULT), 2) AS RE_AVG
    FROM STUDENT ST
    JOIN SCORE SC
      ON ST.SNO = SC.SNO
    GROUP BY ST.MAJOR,
END;
/

EXEC P_MAJOR_AVG_RES;
    SELECT * FROM T_MAJOR_AVG_RES;



--2) 교수들은 부임일로부터 5년마다 안식년을 갖습니다.
--   교수들의 오늘날짜까지의 안식년 횟수를 리턴하는 함수 F_GET_VACATION_CNT를 구현하세요
CREATE OR REPLACE FUNCTION F_GET_VACATION_CNT(
    SABB DATE
)
RETURN NUMBER
IS
    CURR_DATE DATE := SYSDATE;
    VACATION_CNT NUMBER;
BEGIN
    VACATION_CNT := TRUNC(MONTHS_BETWEEN(CURR_DATE, SABB) / 60);
    RETURN VACATION_CNT;
END;
/

SELECT F_GET_VACATION_CNT('1994-02-17') FROM DUAL;



DROP TABLE T_MAJOR_AVG_RES;
DROP TABLE P_MAJOR_AVG_RES;
DROP TABLE T_MAJOR_AVG_RES;